micronaut:
    application:
        name: budgeteer
datasources:
    default:
        url: jdbc:h2:mem:testdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH;DB_CLOSE_DELAY=-1
        username: sa
        password: ''
        driverClassName: org.h2.Driver
        schema-generate: NONE
        dialect: H2
jpa:
    default:
        packages-to-scan:
            - 'com.budgeteer'
        properties:
            hibernate:
                hbm2ddl:
                    auto: validate
                show_sql: true
flyway:
    datasources:
        default:
            enabled: true
            locations:
                - classpath:db/migration