micronaut:
    application:
        name: budgeteer
flyway:
    datasources:
        default:
            enabled: true
            url: jdbc:h2:mem:///testdb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
            username: sa
            password: ''
            driverClassName: org.h2.Driver
            schema-generate: CREATE_DROP
            dialect: H2