CREATE TABLE TRANSACTION (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             transaction_date TIMESTAMP NOT NULL,
                             amount DECIMAL(19,2) NOT NULL,
                             description VARCHAR(255) NOT NULL,
                             merchant VARCHAR(255) NOT NULL,
                             category VARCHAR(100) NOT NULL,
                             original_currency VARCHAR(3) NOT NULL,
                             exchange_rate DECIMAL(19,6),
                             note VARCHAR(500),
                             location VARCHAR(255)
);