CREATE TABLE IF NOT EXISTS transaction (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        transaction_date TIMESTAMP NOT NULL,
        amount DECIMAL NOT NULL,
        description VARCHAR(255) NOT NULL,
        merchant VARCHAR(255) NOT NULL,
        category VARCHAR(255) NOT NULL,
        original_currency VARCHAR(255) NOT NULL,
        exchange_rate DECIMAL,
        note VARCHAR(255),
        location VARCHAR(255)
    );